name: Run Playwright Tests from External Repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      # 1. Checkout the main project (Repo A)
      - name: Checkout app repo
        uses: actions/checkout@v4

      # 2. Checkout the Playwright tests repo (Repo B)
      - name: Checkout tests repo
        uses: actions/checkout@v4
        with:
          repository: nicolasvandemoortele/PlaywrightBUS
          path: tests
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # must have repo read access

      # 3. Set up Node
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4. Install dependencies for the test repo
      - name: Install test dependencies
        working-directory: tests
        run: npm install

      #5. Setup Playwright
      - name: Setup Playwright
        working-directory: tests
        run: npx playwright install

      #6. Create .env file
      - name: Create .env file
        working-directory: tests
        run: |
          echo "BASE_URL=${{ vars.BASE_URL }}" >> .env
          echo "USERNAME=${{ vars.USERNAME }}" >> .env
          echo "PASSWORD=${{ vars.PASSWORD }}" >> .env
          ls -la

      # 7. Run Playwright tests
      - name: Run Playwright tests
        working-directory: tests
        run: npx playwright test --config=playwright.config.ts --grep @Test-1
